Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provision "shell", inline: <<-SHELL
    curl --silent --location https://rpm.nodesource.com/setup | sudo bash -
    yum install -y git nodejs
    git clone https://github.com/redhat-developer-demos/kubernetes-lab.git
    cd kubernetes-lab/frontend
    npm install
    npm start > /var/log/frontend 2>&1 &
  SHELL
end
